name: "[Build] @trezor/suite-web"

on:
  workflow_call:
  push:
    branches:
      - "vd/actions-refactor"

jobs:
  build-web:
    runs-on: ubuntu-latest
    env:
      ASSET_PREFIX: "/suite-web/${{github.head_ref}}/web"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: "Build suite-web"
        run: |
          echo $ASSET_PREFIX
          yarn install --immutable
          yarn workspace @trezor/suite-web build
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: suite-web-build
          path: packages/suite-web/build

  build-landing:
    runs-on: ubuntu-latest
    env:
      ASSET_PREFIX: "/suite-web/${{github.head_ref}}/"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: "Build suite-web landing"
        run: |
          echo $ASSET_PREFIX
          yarn install --immutable
          yarn workspace @trezor/suite-web-landing build
      - name: Upload suite-web build results
        uses: actions/upload-artifact@v3
        with:
          name: suite-web-landing-build
          path: packages/suite-web-landing/build

  deploy-builds:
    needs: [build-web, build-landing]
    runs-on: ubuntu-latest
    env:
      SUITE_DEPLOY_DIRECTORY: "trezorci@dev-suite.do.sldev.cz:/opt/trezor-suite/${{github.head_ref}}/"
    steps:
      - name: Configure ssh credentials
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_SUITE_WEB }}
      - name: Download suite-web build results
        uses: actions/download-artifact@v3
      - name: Upload suite-web and suite-web-landing
        run: |
          rsync --delete -va packages/suite-web-landing/build/ "${SUITE_DEPLOY_DIRECTORY}/"
          rsync --delete -va packages/suite-web/build/ "${SUITE_DEPLOY_DIRECTORY}/web/"
