name: '[Test] Run maestro tests'

on: [pull_request]

jobs:
    run_android_e2e:
        timeout-minutes: 90
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - run: npx envinfo

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 11

            - name: Install Maestro
              run: MAESTRO_VERSION=1.30.4 curl -Ls 'https://get.maestro.mobile.dev' | bash

            - name: Download apk from expo
              run: curl -o suite-native/app/.maestro/testAPKFolder/curlFile.apk https://expo.dev/artifacts/eas/mKNgSp64oreciYb1V2XrvR.apk

            - name: Run Maestro E2E tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 33
                  target: default
                  arch: x86_64
                  cores: 2
                  ram-size: 4096M
                  working-directory: suite-native/app/.maestro
                  force-avd-creation: false
                  emulator-boot-timeout: 900 # 15min
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  pre-emulator-launch-script: |
                      echo "Running pre emulator launch script. Printing the working directory now:"
                      pwd
                  script: |
                      # check memory usage
                      npx envinfo

                      # check location
                      pwd
                      ls -alF

                      # verify emulator is running
                      adb devices

                      # check if file is downloaded
                      ls -alF ./testAPKFolder

                      # Install app
                      adb install -t -r ./testAPKFolder/curlFile.apk || (adb kill-server && adb start-server && adb devices && adb install -t -r ./testAPKFolder/curlFile.apk)

                      # Run e2e
                      maestro test importBTCviaText.yaml
